### ISSUE TITLE
Installing Arch Linux package leaves Pacman database in "inconsistent state"

### ISSUE THREAD

**Issue by blinry** [audapolis/audapolis#340]
I installed the [0.2.1 .pacman release](https://github.com/audapolis/audapolis/releases/download/v0.2.1-1/audapolis-linux-x64-0.2.1-1.pacman) on a moderately up-to-date Arch Linux using `sudo pacman -U audapolis-linux-x64-0.2.1-1.pacman`. This seemed to work, and I could run the application after that.

But after installing the package, running any Pacman operation displays the following error message, without failing the operation:

```
error: local database is inconsistent: name mismatch on package audapolis-0.2.1
error: local database is inconsistent: version mismatch on package audapolis-0.2.1
```

When trying to uninstall the application, I noticed that the name of the package seems to be "audapolis-0.2.1" (including the version number, which is unusual), so I guess something's wrong in the Electron builder pipeline.

Cheers, and thanks for working on this! :)

**Comment by Sch1nken** [comment]
Same issue on Manjaro (Arch based) here.

**Comment by pajowu** [comment]
Digging a bit I found that the problem seems to be that we generate the version numbers as `${Version from package.json}-${Number of Commits since this version was set}` which clashes with archlinux convention to name packages `${Name}-${version}-${counter}`, which becomes `audapolis-0.2.1-1-1`

> Note: pkgver cannot contain spaces or hyphens (-). Using sed to correct this is common.
-- https://wiki.archlinux.org/title/creating_packages#pkgver()

We need to find another scheme of naming our packages @anuejn

**Comment by pajowu** [comment]
We now release a pre-release of the next version that includes the fix for this: https://github.com/audapolis/audapolis/releases/tag/v0.2.1%2B39

We would be happy to hear back from you whether this fixes it
