### ISSUE TITLE
.deb package clang dependency

### ISSUE THREAD

**Issue by mash-graz** [audapolis/audapolis#395]
After installing the v0.2.2-pre2 debian package the application didn't start as expected.

Looking into the debug log, I found this entry:

```
UnixCCompiler__compile\ndistutils.errors.CompileError: Command \"clang -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw -fPIC -c /tmp/tmphgry9_74/source.c -o /tmp/tmphgry9_74/tmp/tmphgry9_74/source.o -MMD -MF /tmp/tmphgry9_74/tmp/tmphgry9_74/source.o.d\" failed with exit status 127\n"]}
```

The reason for this error wasn't hard to guess. There was no `clang` compiler installed on this machine.

To prevent this kind of troubles, please add a dependency entry concerning `clang` to your .deb-package.

**Comment by mash-graz** [comment]
The dependency of `python3.9` while compiling the  punctation module will also cause troubles under `debian testing`, because it's already utilizing `python3.10`

**Comment by pajowu** [comment]
Hey, thanks a lot for reporting, sorry for the late reply. This is a known issue, because our punctuation library currently tries to compile some code during execution. I am currently working on either disabling this compilation (which looks promising ATM, might be able to publish something this week) or disable punctuation for now

**Comment by mash-graz** [comment]
I think, the `clang` dependency issue doesn't belong to the punctuation library, but I may be wrong. At least it blocks the correct initialization of the main application. The other punctuation specific compilation issue (concerning `python3.9` dependency) only happens later, if punctuation processing got enabled.

It could be a useful improvement to report the progress of all this background compilation tasks in a more verbose manner and display errors in the GUI.

And there is another minor issue to report:
The application doesn't show any icon in the application start menu and task bar in the window manager (in may case: cinnamon).

**Comment by pajowu** [comment]
I'm also surprised that the issue came at application start already, since I only experienced problems with the punctuation library and its dependencies once you enable punctuation. But I think that should be the only library which uses clang.

I just tried installing audapolis in a fresh debian 10 installation and did not run into any issues. Could you please send me the debug log, so I can take a look at it? (either upload it here or send it to the email address you can find on https://github.com/audapolis )

**Comment by mash-graz** [comment]
Here is  the debug log of the affected installation:

[debug_log.zip](https://github.com/audapolis/audapolis/files/9658920/debug_log.zip)

Perhaps this `clang` execution is caused by some missing python extension.
It's always a little bit confusing how native installers and language specific package management interfere with debian dependency handling.

**Comment by pajowu** [comment]
Thank you for the file. This confirmed my suspicion that this was caused by punctuator2 (or rather its dependency aesara). Hopefully this should be fixed with https://github.com/audapolis/audapolis/pull/398

**Comment by pajowu** [comment]
I just release v0.2.2-pre3, which includes this fix. Please try again with this version

**Comment by mash-graz** [comment]
Sorry for the delay...

On first sight, everything seems to be fixed! :)

But it's very hard to prove, because old python extension artifacts could be remaining from the previous installation...

Nevertheless, the app and its punctuation feature works fine under `debian testing` and its default python version this time!

thanks!
