### ISSUE TITLE
Won't run on Mac

### ISSUE THREAD

**Issue by jamescridland** [audapolis/audapolis#396]
Would have liked to have played with this, but Chrome kicks up an error when downloading it; and MacOS reports that it can't be opened because Apple can't check it. Wonder if it's signed correctly?

**Comment by pajowu** [comment]
Hey, thanks for reporting this. This is a known issue. It happens because we sign the image with a self-signed key, not one signed by apple and cannot notarize the app. We currently need to do this because we do not have a paid apple developer account at the moment.

You can still run the app on mac with a small trick: Instead of double-clicking to start it, right-click and then select "open". This way you can choose "Open" in the warning dialog about the app not being signed by apple.
